In [1]:
import numpy as np

In [2]:
filepath = "C:\\Users\\LENOVO\\Downloads\\loan-data.csv"

In [3]:
## Remove scientific notation, 
##linewidhth to avoid characters from displaying in 2 rows
## precision to only display 2 decimals
np.set_printoptions(suppress = True, linewidth = 100, precision = True)

In [4]:
## Data frame with header
loan_data_org = np.genfromtxt(filepath, 
                         delimiter = ";",
                         autostrip = True)
loan_data_org

array([[       nan,        nan,        nan, ...,        nan,        nan,        nan],
       [48010226. ,        nan,    35000. , ...,        nan,        nan,     9453. ],
       [57693261. ,        nan,    30000. , ...,        nan,        nan,     4679.7],
       ...,
       [50415990. ,        nan,    10000. , ...,        nan,        nan,     2185.6],
       [46154151. ,        nan,        nan, ...,        nan,        nan,     3199.4],
       [66055249. ,        nan,    10000. , ...,        nan,        nan,      301.9]])

In [5]:
## Skip header removes the 1st column of the data set
## autostrip removes excess whitespaces
loan_data = np.genfromtxt(filepath, 
                         delimiter = ";",
                         skip_header = True,
                         autostrip = True)

In [6]:
## Check for missing value
temporary_fill = np.nanmax(loan_data) + 2
temporary_mean = np.nanmean(loan_data, axis = 0)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12008\3642933820.py:3: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(loan_data, axis = 0)


In [7]:
## Checking if there is any column with non numeric data completely
## nan means the column mean in not a number thus we can tell the column with nana have string character
temporary_mean

array([54015809.2,        nan,    15273.5,        nan,    15311. ,        nan,       16.6,
            440.9,        nan,        nan,        nan,        nan,        nan,     3143.9])

In [8]:
## Check for a few stats along axis 0 ie columns
temporary_stats = np.array([np.nanmin(loan_data, axis = 0),
                           np.nanmean(loan_data, axis = 0),
                           np.nanmax(loan_data, axis = 0)])
temporary_stats

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12008\3800549580.py:2: RuntimeWarning: All-NaN slice encountered
  temporary_stats = np.array([np.nanmin(loan_data, axis = 0),
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12008\3800549580.py:3: RuntimeWarning: Mean of empty slice
  np.nanmean(loan_data, axis = 0),
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12008\3800549580.py:4: RuntimeWarning: All-NaN slice encountered
  np.nanmax(loan_data, axis = 0)])


array([[  373332. ,        nan,     1000. ,        nan,     1000. ,        nan,        6. ,
              31.4,        nan,        nan,        nan,        nan,        nan,        0. ],
       [54015809.2,        nan,    15273.5,        nan,    15311. ,        nan,       16.6,
             440.9,        nan,        nan,        nan,        nan,        nan,     3143.9],
       [68616519. ,        nan,    35000. ,        nan,    35000. ,        nan,       29. ,
            1373. ,        nan,        nan,        nan,        nan,        nan,    41913.6]])

## We want to seperate the column with "str" from those with "int" 

In [9]:
## We'll use the temporary_mean variable to tell the columns with nill value
## Return columns with string characters only
## To display the output in a row we use squeeze methods
string_column = np.argwhere(np.isnan(temporary_mean)).squeeze()
string_column

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [10]:
## To do the same with columns with int
int_col = np.argwhere(np.isnan(temporary_mean) == False).squeeze()
int_col

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

In [11]:
## Lets create an array with only string characters
loan_data_str = np.genfromtxt(filepath,
                             delimiter = ";",
                             skip_header = True,
                             autostrip = True,
                             usecols = string_column,
                             dtype =  str)
loan_data_str

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [12]:
## Lets create an array with only string characters
loan_data_int = np.genfromtxt(filepath,
                             delimiter = ";",
                             skip_header = True,
                             autostrip = True,
                             usecols = int_col,
                             dtype =  np.int32, 
                             filling_values = temporary_fill)
loan_data_int

array([[48010226,    35000,    35000,       13,     1184,     9452],
       [57693261,    30000,    30000, 68616521,      938,     4679],
       [59432726,    15000,    15000, 68616521,      494,     1969],
       ...,
       [50415990,    10000,    10000, 68616521, 68616521,     2185],
       [46154151, 68616521,    10000,       16,      354,     3199],
       [66055249,    10000,    10000, 68616521,      309,      301]])

In [13]:
## Import columns only
header = np.genfromtxt(filepath,
                      delimiter = ";",
                      autostrip = True,
                      skip_footer = loan_data.shape[0],
                      dtype = str)
header

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [14]:
## assighning column names to our desired dataframe
header_int, header_str = header[int_col],header[string_column]

In [15]:
print(header_int)
print(header_str)

['id' 'loan_amnt' 'funded_amnt' 'int_rate' 'installment' 'total_pymnt']
['issue_d' 'loan_status' 'term' 'grade' 'sub_grade' 'verification_status' 'url' 'addr_state']


## Manupulating String Columns

In [16]:
header_str[0], header_str[7]= "issue_date", "state_address"
header_str[0]

'issue_date'

## issue_date

In [17]:
## We'd like months to have their numeric order is jan to 1 and dec 12
## 1st let check the unique value in the column
## We have a '' blank value before 'Apr-15'
np.unique(loan_data_str[:, 0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [18]:
## Let's strip of the -15 from the entire column
loan_data_str[:, 0] = np.chararray.strip(loan_data_str[:, 0], "-15")
np.unique(loan_data_str[:, 0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [19]:
## Create a variale months
## the variable we are replacing with are in an np.array
months =np.array (['', 'Jan', 'Feb','Mar','Apr', 'May', 'Jun', 'Jul','Aug','Sep','Oct','Nov', 'Dec'])
months

array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
      dtype='<U3')

In [20]:
## Iterate thru' the column to replace the months with numbers
for i in range(13):
    loan_data_str[:, 0] = np.where(loan_data_str[:, 0] == months[i],
                                  i,
                                  loan_data_str[:, 0])

In [21]:
np.unique(loan_data_str[:, 0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

## loan_status

In [22]:
np.unique(loan_data_str[:, 1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [23]:
## to check the number of unique elements in the column
np.unique(loan_data_str[:, 1]).size

9

In [24]:
## Will have good and bad status "1" will represent the good status whereas "0" will represent/replace the bad loanstutus
statusBad = (['','Charged Off','Default','Late (31-120 days)'])

In [25]:
loan_data_str[:, 1] = np.where(np.isin(loan_data_str[:, 1], statusBad), 0, 1)

In [26]:
loan_data_str

array([['5', '1', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['0', '1', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['9', '1', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['6', '1', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['4', '1', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['12', '1', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

### Term


In [27]:
np.unique(loan_data_str[:, 2])

array(['', '36 months', '60 months'], dtype='<U69')

In [28]:
## Let's remove months frome the column term
loan_data_str[:, 2] = np.chararray.strip(loan_data_str[:, 2], ' months')
loan_data_str[:, 2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [29]:
header_str[2] = "monthTerms"
header_str

array(['issue_date', 'loan_status', 'monthTerms', 'grade', 'sub_grade', 'verification_status',
       'url', 'state_address'], dtype='<U19')

In [30]:
### Change data type to string to make it possible to substitute "60" with blanks
loan_data_str

array([['5', '1', '36', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['0', '1', '36', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['9', '1', '36', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['6', '1', '36', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['4', '1', '36', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['12', '1', '36', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [31]:
## Lets replace all blank values with "60" as a common practise principal in credit risk modeling
loan_data_str[:, 2] = np.where(loan_data_str[:, 2] == '',
                              60, 
                             loan_data_str[:, 2])
np.unique(loan_data_str[:, 2])

array(['36', '60'], dtype='<U69')

### Grade and Subgrade

In [32]:
np.unique(loan_data_str[:, 3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [33]:
np.unique(loan_data_str[:, 4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [34]:
### Will replace all values in substring string column with a letter from the grade column and add 5 
for i in np.unique(loan_data_str[:, 3])[1:]:
    loan_data_str[:, 4] = np.where((loan_data_str[:, 4] == "") & (loan_data_str[:, 3] == i),
                                             i + "5",
                                             loan_data_str[:, 4])
np.unique(loan_data_str[:, 4], return_counts = True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5],
       dtype=int64))

In [35]:
### Check the number of times each element appears
array_test = np.array(np.unique(loan_data_str[:, 3], return_counts = True))
array_test

array([['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'],
       ['515', '1632', '2606', '2766', '1389', '816', '236', '40']], dtype='<U69')

In [36]:
array_test[1] = array_test[1].astype(np.int32)
array_test[1]

array(['515', '1632', '2606', '2766', '1389', '816', '236', '40'], dtype='<U69')

In [37]:
### this is how you check the maximum value of a string array
max(array_test[1])

'816'

In [38]:
loan_data_str[:, 4] = np.where((loan_data_str[:, 4] == ""),
                               "H5",
                               loan_data_str[:, 4])
np.unique(loan_data_str[:, 4], return_counts = True)

(array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
        'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
        'G1', 'G2', 'G3', 'G4', 'G5', 'H5'], dtype='<U69'),
 array([285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267, 250,
        255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5,   9],
       dtype=int64))

In [39]:
loan_data_str = np.delete(loan_data_str, 3, axis = 1)
loan_data_str[:, 3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [40]:
header_str = np.delete(header_str, 3, axis = 0)
header_str

array(['issue_date', 'loan_status', 'monthTerms', 'sub_grade', 'verification_status', 'url',
       'state_address'], dtype='<U19')

In [41]:
# Assighn a value to each of the character strings in "loan_data_str[:, 3]"
np.unique(loan_data_str[:, 3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H5'], dtype='<U69')

In [42]:
print(list(np.unique(loan_data_str[:, 3])))

['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2', 'G3', 'G4', 'G5', 'H5']


In [43]:
r = list(np.unique(loan_data_str[:, 3]))
print(r)

['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2', 'G3', 'G4', 'G5', 'H5']


In [44]:
t = range(1, 5)
print(np.count_nonzero(r))
print(r)

36
['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2', 'G3', 'G4', 'G5', 'H5']


In [45]:
## Check array output shape
### ".shape[0]" returns the number of rows,[0] represents the rows axis , 
### if it was a 2d array [1] would represnt the number of columns
np.unique(loan_data_str[:, 3]).shape[0]

36

In [46]:
## To check the number of unique values in the array
x = np.unique(loan_data_str[:, 3])
y = np.count_nonzero(x)
y

36

In [47]:
z = y + 1
z

37

In [48]:
### assighn a value to each unique character in sub_grade column
values = list(range(1, z))
print(values)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36]


In [49]:
### "zip" function takes two or more iterables and pairs their elements together
### It creates an iterator that generates tuples where the i-th tuple contains the i-th element from each of the input iterables.
dict_sub_grade = dict(zip(r, values))
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H5': 36}

In [50]:
for i in x:
    loan_data_str[:, 3] = np.where(loan_data_str[:, 3] == i,
                                  dict_sub_grade[i],
                                  loan_data_str[:, 3])

In [51]:
np.unique(loan_data_str[:, 3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Verification status  and URL

In [52]:
loan_data_str[:, 4]

array(['Verified', 'Source Verified', 'Verified', ..., 'Source Verified', 'Source Verified', ''],
      dtype='<U69')

In [53]:
np.unique(loan_data_str[:, 4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [54]:
loan_data_str[:, 4] = np.where((loan_data_str[:, 4]  == '') | (loan_data_str[:, 4] == 'Not Verified'), 0, loan_data_str[:, 4])
loan_data_str[:, 4]

array(['Verified', 'Source Verified', 'Verified', ..., 'Source Verified', 'Source Verified', '0'],
      dtype='<U69')

In [55]:
np.unique(loan_data_str[:, 4])

array(['0', 'Source Verified', 'Verified'], dtype='<U69')

In [56]:
loan_data_str[:, 4] = np.where((loan_data_str[:, 4] == 'Source Verified') | (loan_data_str[:, 4] == 'Verified'), 1, loan_data_str[:, 4])
np.unique(loan_data_str[:, 4], return_counts = True)

(array(['0', '1'], dtype='<U69'), array([3173, 6827], dtype=int64))

In [57]:
### Check verification status column
loan_data_str[:, 5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [58]:
loan_data_str[:, 5] = np.chararray.strip(loan_data_str[:, 5], "https://www.lendingclub.com/browse/loanDetail.action?loan_id=")
loan_data_str[:, 5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [59]:
loan_data_int[:, 0]

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [60]:
loan_data_str[:, 5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [61]:
## This 2 arrays have the same the same output except one has string values the other has interger value
loan_data_int.dtype

dtype('int32')

In [62]:
np.unique(loan_data_str[:, 5])

array(['12606806', '13026045', '1312426', ..., '8138291', '8214572', '849994'], dtype='<U69')

In [63]:
### To change the data type of "loan_data_str[:, 5]"
loan_data_str[:, 5] = loan_data_str[:, 5].astype(np.int32)
loan_data_str[:, 5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [64]:
np.equal(loan_data_int[:, 0], loan_data_str[:, 5].astype(dtype = int))


array([ True,  True,  True, ...,  True,  True,  True])

In [65]:
### further we could use this function
np.array_equal(loan_data_int[:, 0], loan_data_str[:, 5].astype(dtype = int))

True

In [66]:
loan_data_str = np.delete(loan_data_str, 5 ,axis = 1)

In [67]:
loan_data_str

array([['5', '1', '36', '13', '1', 'CA'],
       ['0', '1', '36', '5', '1', 'NY'],
       ['9', '1', '36', '10', '1', 'PA'],
       ...,
       ['6', '1', '36', '5', '1', 'CA'],
       ['4', '1', '36', '17', '1', 'OH'],
       ['12', '1', '36', '4', '0', 'IL']], dtype='<U69')

In [68]:
header_str = np.delete(header_str, 5, axis = 0)
header_str

array(['issue_date', 'loan_status', 'monthTerms', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

### State Address

In [69]:
## Check the state address elements, notice the missing value`
np.unique(loan_data_str[:, 5])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [70]:
## To check the number unique values in the the "loan_data_str[:, 5]"
## Which is equivalent to the number of statess in the US,  we however have one that is missing "Iowa/ Ia"
np.unique(loan_data_str[:, 5]).size

50

In [71]:
### To check the number of time each state appears
np.unique(loan_data_str[:, 5], return_counts = True)

(array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
        'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
        'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
        'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'),
 array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,
          84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,
         341,   57,  130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,
          17,  216,  148,   49,   27], dtype=int64))

In [72]:
## let'sort the number of state application is descending order
states_countAndname = np.array(np.unique(loan_data_str[:, 5], return_counts = True))
states_countAndname

array([['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
        'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
        'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
        'VT', 'WA', 'WI', 'WV', 'WY'],
       ['500', '26', '119', '74', '220', '1336', '201', '143', '27', '27', '690', '321', '44',
        '389', '152', '84', '84', '116', '210', '222', '10', '267', '156', '160', '61', '28',
        '261', '16', '25', '58', '341', '57', '130', '777', '312', '83', '108', '320', '40',
        '107', '24', '143', '758', '74', '242', '17', '216', '148', '49', '27']], dtype='<U69')

In [73]:
states_countAndname.shape

(2, 50)

In [74]:
states_countAndname = states_countAndname.transpose()
states_countAndname

array([['', '500'],
       ['AK', '26'],
       ['AL', '119'],
       ['AR', '74'],
       ['AZ', '220'],
       ['CA', '1336'],
       ['CO', '201'],
       ['CT', '143'],
       ['DC', '27'],
       ['DE', '27'],
       ['FL', '690'],
       ['GA', '321'],
       ['HI', '44'],
       ['IL', '389'],
       ['IN', '152'],
       ['KS', '84'],
       ['KY', '84'],
       ['LA', '116'],
       ['MA', '210'],
       ['MD', '222'],
       ['ME', '10'],
       ['MI', '267'],
       ['MN', '156'],
       ['MO', '160'],
       ['MS', '61'],
       ['MT', '28'],
       ['NC', '261'],
       ['ND', '16'],
       ['NE', '25'],
       ['NH', '58'],
       ['NJ', '341'],
       ['NM', '57'],
       ['NV', '130'],
       ['NY', '777'],
       ['OH', '312'],
       ['OK', '83'],
       ['OR', '108'],
       ['PA', '320'],
       ['RI', '40'],
       ['SC', '107'],
       ['SD', '24'],
       ['TN', '143'],
       ['TX', '758'],
       ['UT', '74'],
       ['VA', '242'],
       ['VT', '17'],
       [

In [75]:
### lets sort is an assending order
states_countAndname = states_countAndname[np.argsort(states_countAndname[:, 1].astype(np.int32))]
states_countAndname

array([['ME', '10'],
       ['ND', '16'],
       ['VT', '17'],
       ['SD', '24'],
       ['NE', '25'],
       ['AK', '26'],
       ['WY', '27'],
       ['DC', '27'],
       ['DE', '27'],
       ['MT', '28'],
       ['RI', '40'],
       ['HI', '44'],
       ['WV', '49'],
       ['NM', '57'],
       ['NH', '58'],
       ['MS', '61'],
       ['UT', '74'],
       ['AR', '74'],
       ['OK', '83'],
       ['KY', '84'],
       ['KS', '84'],
       ['SC', '107'],
       ['OR', '108'],
       ['LA', '116'],
       ['AL', '119'],
       ['NV', '130'],
       ['CT', '143'],
       ['TN', '143'],
       ['WI', '148'],
       ['IN', '152'],
       ['MN', '156'],
       ['MO', '160'],
       ['CO', '201'],
       ['MA', '210'],
       ['WA', '216'],
       ['AZ', '220'],
       ['MD', '222'],
       ['VA', '242'],
       ['NC', '261'],
       ['MI', '267'],
       ['OH', '312'],
       ['PA', '320'],
       ['GA', '321'],
       ['NJ', '341'],
       ['IL', '389'],
       ['', '500'],
       ['FL

In [76]:
## Lets sort in ascending order, to sort in descending order we add "[::-1]"
states_countAndname = states_countAndname[np.argsort(states_countAndname[:, 1].astype(np.int32))[::-1]]
states_countAndname

array([['CA', '1336'],
       ['NY', '777'],
       ['TX', '758'],
       ['FL', '690'],
       ['', '500'],
       ['IL', '389'],
       ['NJ', '341'],
       ['GA', '321'],
       ['PA', '320'],
       ['OH', '312'],
       ['MI', '267'],
       ['NC', '261'],
       ['VA', '242'],
       ['MD', '222'],
       ['AZ', '220'],
       ['WA', '216'],
       ['MA', '210'],
       ['CO', '201'],
       ['MO', '160'],
       ['MN', '156'],
       ['IN', '152'],
       ['WI', '148'],
       ['TN', '143'],
       ['CT', '143'],
       ['NV', '130'],
       ['AL', '119'],
       ['LA', '116'],
       ['OR', '108'],
       ['SC', '107'],
       ['KS', '84'],
       ['KY', '84'],
       ['OK', '83'],
       ['AR', '74'],
       ['UT', '74'],
       ['MS', '61'],
       ['NH', '58'],
       ['NM', '57'],
       ['WV', '49'],
       ['HI', '44'],
       ['RI', '40'],
       ['MT', '28'],
       ['DE', '27'],
       ['DC', '27'],
       ['WY', '27'],
       ['AK', '26'],
       ['NE', '25'],
      

In [77]:
## Now lets group states 
## iowa being bank will assighn a zero to it
loan_data_str[:, 5] = np.where(loan_data_str[:, 5] == "",
                              0,
                              loan_data_str[:, 5])
np.unique(loan_data_str[:, 5])

array(['0', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [78]:
states_west = np.array(['WA', 'OR', 'CA', 'NV', 'ID', 'MT', 'WY', 'UT', 'CO', 'AZ', 'NM', 'HI', 'AK'])
states_south = np.array(['TX', 'OK', 'AR','LA', 'MS', 'AL', 'TN', 'KY', 'FL', 'SC', 'GA', 'NC', 'VA','WV', 'MD', 'DE', 'DC'])
states_midwest = np.array(['ND', 'SD', 'NE', 'KS', 'MN', 'IA', 'MD', 'WI','IL', 'IN', 'MI', 'OH'])
states_east = np.array(['PA', 'NY', 'NJ', 'CT', 'MA', 'VT', 'NH', 'ME', 'RI'])

In [79]:
## To replace this we'll the values in "loan_data_str[:, 5]"
loan_data_str[:, 5] = np.where(np.isin(loan_data_str[:, 5], states_west), 1, loan_data_str[:, 5])
loan_data_str[:, 5] = np.where(np.isin(loan_data_str[:, 5], states_south), 2, loan_data_str[:, 5])
loan_data_str[:, 5] = np.where(np.isin(loan_data_str[:, 5], states_midwest), 3, loan_data_str[:, 5])
loan_data_str[:, 5] = np.where(np.isin(loan_data_str[:, 5], states_east), 4, loan_data_str[:, 5])

In [80]:
np.unique(loan_data_str[:, 5])

array(['0', '1', '2', '3', '4', 'MO'], dtype='<U69')

In [81]:
loan_data_str[:, 5] = np.where(loan_data_str[:, 5] == "MO",
                              3,
                              loan_data_str[:, 5])
np.unique(loan_data_str[:, 5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

In [82]:
np.unique(loan_data_str[:, 5], return_counts = True)

(array(['0', '1', '2', '3', '4'], dtype='<U69'),
 array([ 500, 2467, 3384, 1733, 1916], dtype=int64))

### Convert string with numeric characters into integers

In [83]:
### Convert the numeric data saved as text in int.
loan_data_str

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

### Manupulating Numeric Columns

In [84]:
loan_data_int

array([[48010226,    35000,    35000,       13,     1184,     9452],
       [57693261,    30000,    30000, 68616521,      938,     4679],
       [59432726,    15000,    15000, 68616521,      494,     1969],
       ...,
       [50415990,    10000,    10000, 68616521, 68616521,     2185],
       [46154151, 68616521,    10000,       16,      354,     3199],
       [66055249,    10000,    10000, 68616521,      309,      301]])

In [85]:
np.isnan(loan_data_int).sum()

0

In [86]:
header_int

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

### Id

In [87]:
temporary_fill

68616521.0

In [88]:
### Check if we have temporary fill in the Id column
np.isin(loan_data_int[:, 0], temporary_fill).sum()

0

In [89]:
## temporary_stats
## the columns represent the min, mean and max in the the respective order.
## min being on top
temporary_stats

array([[  373332. ,        nan,     1000. ,        nan,     1000. ,        nan,        6. ,
              31.4,        nan,        nan,        nan,        nan,        nan,        0. ],
       [54015809.2,        nan,    15273.5,        nan,    15311. ,        nan,       16.6,
             440.9,        nan,        nan,        nan,        nan,        nan,     3143.9],
       [68616519. ,        nan,    35000. ,        nan,    35000. ,        nan,       29. ,
            1373. ,        nan,        nan,        nan,        nan,        nan,    41913.6]])

In [90]:
temporary_stats[:, int_col]

array([[  373332. ,     1000. ,     1000. ,        6. ,       31.4,        0. ],
       [54015809.2,    15273.5,    15311. ,       16.6,      440.9,     3143.9],
       [68616519. ,    35000. ,    35000. ,       29. ,     1373. ,    41913.6]])

In [91]:
print(temporary_stats[:, int_col].shape)

(3, 6)


In [92]:
### lets check the position of eah element
np.argwhere(temporary_stats[:, int_col]).squeeze()

array([[0, 0],
       [0, 1],
       [0, 2],
       [0, 3],
       [0, 4],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 3],
       [1, 4],
       [1, 5],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3],
       [2, 4],
       [2, 5]], dtype=int64)

In [93]:
print(temporary_stats[:, int_col[2]])
print(temporary_stats[0, int_col[2]])

[ 1000. 15311. 35000.]
1000.0


### funded_amnt

In [94]:
loan_data_int[:, 2]

array([35000, 30000, 15000, ..., 10000, 10000, 10000])

In [95]:
loan_data_int[:, 2] = np.where(loan_data_int[:, 2] == temporary_fill,
                              temporary_stats[0, int_col[2]],
                              loan_data_int[:, 2])
loan_data_int[:, 2]

array([35000, 30000, 15000, ..., 10000, 10000, 10000])

In [96]:
### Let's see each header element and it's position
### We'd like to replace missing values/temporary_fill in "loan_amnt", "int_rate", "installment", "total_pymnt"
### with max values
h = header_int
j = np.argwhere(header_int)
k = dict(zip(h, j))
k

{'id': array([0], dtype=int64),
 'loan_amnt': array([1], dtype=int64),
 'funded_amnt': array([2], dtype=int64),
 'int_rate': array([3], dtype=int64),
 'installment': array([4], dtype=int64),
 'total_pymnt': array([5], dtype=int64)}

In [97]:
l = np.array([1, 3, 4, 5])
l

array([1, 3, 4, 5])

In [98]:
for i in l:
    loan_data_int[:, i] = np.where(loan_data_int[: ,i] == temporary_fill,
                               temporary_stats[2, int_col[i]],
                               loan_data_int[:, i])

In [99]:
loan_data_int

array([[48010226,    35000,    35000,       13,     1184,     9452],
       [57693261,    30000,    30000,       28,      938,     4679],
       [59432726,    15000,    15000,       28,      494,     1969],
       ...,
       [50415990,    10000,    10000,       28,     1372,     2185],
       [46154151,    35000,    10000,       16,      354,     3199],
       [66055249,    10000,    10000,       28,      309,      301]])

In [100]:
filepath1 = "C:\\Users\\LENOVO\\Downloads\\EUR-USD.csv"

In [101]:
## This data set, represents the exchange rate for the year.
## Shows the the open, high low and rate at the close of every  month.  
EUR_USD_org = np.genfromtxt(filepath1, 
                       delimiter = ",",
                       autostrip = True, 
                       dtype = str)
EUR_USD_org

array([['Open', 'High', 'Low', 'Close', 'Volume'],
       ['1.2098628282546997', '1.2098628282546997', '1.11055588722229', '1.1287955045700073', '0'],
       ['1.1287955045700073', '1.1484194993972778', '1.117680549621582', '1.1205360889434814',
        '0'],
       ['1.119795799255371', '1.1240400075912476', '1.0460032224655151', '1.0830246210098267',
        '0'],
       ['1.0741022825241089', '1.1247594356536865', '1.0521597862243652', '1.1114321947097778',
        '0'],
       ['1.1215037107467651', '1.145304799079895', '1.0821995735168457', '1.0960345268249512',
        '0'],
       ['1.095902442932129', '1.1428401470184326', '1.0888904333114624', '1.122296690940857', '0'],
       ['1.1134989261627197', '1.1219995021820068', '1.081270456314087', '1.0939244031906128',
        '0'],
       ['1.0969001054763794', '1.1705996990203857', '1.0850305557250977', '1.1340054273605347',
        '0'],
       ['1.1225990056991577', '1.1460003852844238', '1.1089695692062378', '1.1255937814712524

In [102]:
## We are not inrested in in the volume column so we'll import the data set without the it
EUR_USD = np.genfromtxt(filepath1, 
                       delimiter = ",",
                       autostrip = True,
                       skip_header = 1, 
                       usecols = 3, 
                       dtype = str)
EUR_USD

array(['1.1287955045700073', '1.1205360889434814', '1.0830246210098267', '1.1114321947097778',
       '1.0960345268249512', '1.122296690940857', '1.0939244031906128', '1.1340054273605347',
       '1.1255937814712524', '1.100897192955017', '1.0583018064498901', '1.093398094177246'],
      dtype='<U18')

In [103]:
EUR_USD.shape

(12,)

In [104]:
np.round(EUR_USD.astype(dtype = np.float64), decimals = 2 )

array([1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1])

In [105]:
print(loan_data_str[:, 0])
print(header_str[0])

['5' '0' '9' ... '6' '4' '12']
issue_date


In [106]:
### to check how many unique variables are there 
np.count_nonzero(np.unique(loan_data_str[:, 0]))

13

In [107]:
## We are not inrested in in the volume column so we'll import the data set without the it
EUR_USD = np.genfromtxt(filepath1, 
                       delimiter = ",",
                       autostrip = True,
                       skip_header = 1, 
                       usecols = 3, 
                       dtype = str)
EUR_USD

array(['1.1287955045700073', '1.1205360889434814', '1.0830246210098267', '1.1114321947097778',
       '1.0960345268249512', '1.122296690940857', '1.0939244031906128', '1.1340054273605347',
       '1.1255937814712524', '1.100897192955017', '1.0583018064498901', '1.093398094177246'],
      dtype='<U18')

In [108]:
EUR_USD = EUR_USD.astype(dtype = np.float64)
EUR_USD

array([1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1])

In [109]:
### Let's create a new column, call it  "exchange_rate"
exchange_rate = loan_data_str[:, 0]
exchange_rate

array(['5', '0', '9', ..., '6', '4', '12'], dtype='<U69')

In [110]:
exchange_rate = exchange_rate.astype(dtype = int)
exchange_rate

array([ 5,  0,  9, ...,  6,  4, 12])

In [111]:
exchange_rate.shape

(10000,)

In [112]:
p = np.mean(EUR_USD)
p

1.1056866943836212

In [113]:
## Lets replace the "0" zero values in exchange rate with the mean of "EUR_USD"
### When it's a one dimentional array ypu don't have to place [i] in
exchange_rate = np.where(exchange_rate == 0,
                         p,
                         exchange_rate)
exchange_rate

array([ 5. ,  1.1,  9. , ...,  6. ,  4. , 12. ])

In [114]:
# we'd like to have every month with with it's corresponding exchange rate from 'EUR_USD' dataset
# We'll replace the every month in the new exchange_rate np array with it's corresponding exchange rate

for i in range(1, 13):
    exchange_rate = np.where(exchange_rate == i,
                               EUR_USD[i-1],
                               exchange_rate)
    
exchange_rate

array([1.1, 1.1, 1.1, ..., 1.1, 1.1, 1.1])

In [115]:
## we'll ad the "exchange_rate" to the "loan_data_int"
## We can perform a horizontal stack to the "loan_data_int"
print(exchange_rate.shape)
print(loan_data_int.shape)

(10000,)
(10000, 6)


In [116]:
exchange_rate.transpose().shape

(10000,)

In [117]:
## Transponse does not work
## So we use reshape
## You have to specify the shape of the output
exchange_rate.reshape(10000, 1)

array([[1.1],
       [1.1],
       [1.1],
       ...,
       [1.1],
       [1.1],
       [1.1]])

In [118]:
exchange_rate =  exchange_rate.reshape(10000, 1)
exchange_rate.shape

(10000, 1)

In [119]:
### The hstack works only if the array have the same dimension
## Notice the double brackets
loan_data_int = np.hstack((loan_data_int, exchange_rate))
loan_data_int

array([[48010226. ,    35000. ,    35000. , ...,     1184. ,     9452. ,        1.1],
       [57693261. ,    30000. ,    30000. , ...,      938. ,     4679. ,        1.1],
       [59432726. ,    15000. ,    15000. , ...,      494. ,     1969. ,        1.1],
       ...,
       [50415990. ,    10000. ,    10000. , ...,     1372. ,     2185. ,        1.1],
       [46154151. ,    35000. ,    10000. , ...,      354. ,     3199. ,        1.1],
       [66055249. ,    10000. ,    10000. , ...,      309. ,      301. ,        1.1]])

In [120]:
loan_data_int[:, 6]

array([1.1, 1.1, 1.1, ..., 1.1, 1.1, 1.1])

In [121]:
## Let's also add exchange_rate in the header_str
header_int

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [122]:
### Let's concat to join the exchange rate column
### Notice the double brackets

## header_int = np.concatenate((header_int, "exchange_rate"))

### From USD to EUR

In [123]:
header_int = np.concatenate((header_int, np.array(["exchange_rate"])))
header_int

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [124]:
## Column with "amnt" suffix have their amounts in dolars also installment and payment
dollar_column = np.array([1, 2, 4, 5])

In [125]:
dollar_columns = loan_data_int[:, dollar_column]
dollar_columns

array([[35000., 35000.,  1184.,  9452.],
       [30000., 30000.,   938.,  4679.],
       [15000., 15000.,   494.,  1969.],
       ...,
       [10000., 10000.,  1372.,  2185.],
       [35000., 10000.,   354.,  3199.],
       [10000., 10000.,   309.,   301.]])

In [126]:
e_rate = loan_data_int[:, 6]
e_rate

array([1.1, 1.1, 1.1, ..., 1.1, 1.1, 1.1])

In [127]:
### Lets create a new data frame that has the above values as in Euros
EUR_df = dollar_columns / (e_rate.reshape(10000, 1)) 
EUR_df

array([[31933.3, 31933.3,  1080.3,  8623.8],
       [27132.5, 27132.5,   848.3,  4231.8],
       [13326.3, 13326.3,   438.9,  1749.3],
       ...,
       [ 8910.3,  8910.3,  1222.5,  1946.9],
       [31490.9,  8997.4,   318.5,  2878.3],
       [ 9145.8,  9145.8,   282.6,   275.3]])

In [128]:
loan_data_int = np.hstack((loan_data_int, EUR_df))
loan_data_int

array([[48010226. ,    35000. ,    35000. , ...,    31933.3,     1080.3,     8623.8],
       [57693261. ,    30000. ,    30000. , ...,    27132.5,      848.3,     4231.8],
       [59432726. ,    15000. ,    15000. , ...,    13326.3,      438.9,     1749.3],
       ...,
       [50415990. ,    10000. ,    10000. , ...,     8910.3,     1222.5,     1946.9],
       [46154151. ,    35000. ,    10000. , ...,     8997.4,      318.5,     2878.3],
       [66055249. ,    10000. ,    10000. , ...,     9145.8,      282.6,      275.3]])

In [129]:
loan_data_int.shape

(10000, 11)

In [130]:
header_int

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [131]:
## Lets add the four column names to the 'header_int'
headerEur = np.array([ i + 'EUR'  for i in header_int[dollar_column]])
headerEur

array(['loan_amntEUR', 'funded_amntEUR', 'installmentEUR', 'total_pymntEUR'], dtype='<U14')

In [132]:
header_int = np.concatenate((header_int, headerEur))
header_int

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amntEUR', 'funded_amntEUR', 'installmentEUR', 'total_pymntEUR'], dtype='<U19')

In [133]:
### Let's add USD to the columns with "loan_amnt","funded_amnt", "installment", "total_pymnt"
header_int[dollar_column] = np.array([i + "USD" for i in header_int[dollar_column]])
header_int

array(['id', 'loan_amntUSD', 'funded_amntUSD', 'int_rate', 'installmentUSD', 'total_pymntUSD',
       'exchange_rate', 'loan_amntEUR', 'funded_amntEUR', 'installmentEUR', 'total_pymntEUR'],
      dtype='<U19')

In [134]:
### Let's put each column with USD and EUR next to each other
t = header_int
p = np.argwhere(header_int)
pos = dict(zip(t,p))
pos

{'id': array([0], dtype=int64),
 'loan_amntUSD': array([1], dtype=int64),
 'funded_amntUSD': array([2], dtype=int64),
 'int_rate': array([3], dtype=int64),
 'installmentUSD': array([4], dtype=int64),
 'total_pymntUSD': array([5], dtype=int64),
 'exchange_rate': array([6], dtype=int64),
 'loan_amntEUR': array([7], dtype=int64),
 'funded_amntEUR': array([8], dtype=int64),
 'installmentEUR': array([9], dtype=int64),
 'total_pymntEUR': array([10], dtype=int64)}

In [135]:
order = np.array([0, 1, 7, 2, 8, 3, 4, 9, 5, 10, 6])
order

array([ 0,  1,  7,  2,  8,  3,  4,  9,  5, 10,  6])

In [136]:
header_int = header_int[order]
header_int

array(['id', 'loan_amntUSD', 'loan_amntEUR', 'funded_amntUSD', 'funded_amntEUR', 'int_rate',
       'installmentUSD', 'installmentEUR', 'total_pymntUSD', 'total_pymntEUR', 'exchange_rate'],
      dtype='<U19')

In [137]:
loan_data_int = loan_data_int[:, order]
loan_data_int

array([[48010226. ,    35000. ,    31933.3, ...,     9452. ,     8623.8,        1.1],
       [57693261. ,    30000. ,    27132.5, ...,     4679. ,     4231.8,        1.1],
       [59432726. ,    15000. ,    13326.3, ...,     1969. ,     1749.3,        1.1],
       ...,
       [50415990. ,    10000. ,     8910.3, ...,     2185. ,     1946.9,        1.1],
       [46154151. ,    35000. ,    31490.9, ...,     3199. ,     2878.3,        1.1],
       [66055249. ,    10000. ,     9145.8, ...,      301. ,      275.3,        1.1]])

### "int_rate" / Interest Rate


In [138]:
### Lets have the interest rate as a decimal rather than as a percentage
header_int[5] = " Interest_Rate"
header_int

array(['id', 'loan_amntUSD', 'loan_amntEUR', 'funded_amntUSD', 'funded_amntEUR', ' Interest_Rate',
       'installmentUSD', 'installmentEUR', 'total_pymntUSD', 'total_pymntEUR', 'exchange_rate'],
      dtype='<U19')

In [139]:
loan_data_int[:, 5]

array([13., 28., 28., ..., 28., 16., 28.])

In [140]:
loan_data_int[:, 5] = loan_data_int[:, 5]/100
loan_data_int[:, 5]

array([0.1, 0.3, 0.3, ..., 0.3, 0.2, 0.3])

In [141]:
### To print everything in a numy array
np.set_printoptions(threshold=np.inf)

In [142]:
### To restore default
np.set_printoptions(threshold=1000)
loan_data_int[:, 5]

array([0.1, 0.3, 0.3, ..., 0.3, 0.2, 0.3])

### Combine the data into one dataset

In [143]:
print(loan_data_int.shape)
print(loan_data_str.shape)

(10000, 11)
(10000, 6)


In [144]:
loan_data = np.hstack((loan_data_int, loan_data_str))
loan_data.shape

(10000, 17)

In [145]:
### Lets combine the headers as well
header_full = np.concatenate((header_int, header_str))
header_full.shape

(17,)

In [146]:
header_full

array(['id', 'loan_amntUSD', 'loan_amntEUR', 'funded_amntUSD', 'funded_amntEUR', ' Interest_Rate',
       'installmentUSD', 'installmentEUR', 'total_pymntUSD', 'total_pymntEUR', 'exchange_rate',
       'issue_date', 'loan_status', 'monthTerms', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [147]:
### Combine the header with the dataset
loan_data = np.vstack((header_full, loan_data))

In [148]:
loan_data.shape

(10001, 17)

In [149]:
## Export the dataset
np.savetxt("loan_data_clean.csv", 
           loan_data,
           fmt = "%s",
          delimiter = ",")

### Check working directory

In [150]:
import os
os.getcwd()

'C:\\Users\\LENOVO\\Python Projects'